import type { CompetitiveMarketScenarioContent, MarketIntensity, MarketPolicyType } from '../../types/competitive-market';
import { Check, LinesField, NumberField, TextField } from '../scenarios/fields';

const roles = ['BUYER','SELLER','GOVERNMENT'] as const;
const actions = ['SUBMIT_BUYER_BID','SUBMIT_SELLER_ASK','SUBMIT_MARKET_PREDICTION'] as const;
const policies: MarketPolicyType[] = ['None','PriceCeiling','PriceFloor','PerUnitTax','PerUnitSubsidy'];
const intensities: MarketIntensity[] = ['Mild','Moderate','Strong'];
const assessment = [[0,'Equilibrium reasoning'],[1,'Demand and supply reasoning'],[2,'Elasticity'],[3,'Consumer and producer surplus'],[4,'Tax incidence'],[5,'Price controls'],[6,'Causal market reasoning']] as const;
export const blankMarket = (): CompetitiveMarketScenarioContent => ({ briefing:'', learningObjectives:[], discussionPrompts:[], debriefPrompts:[], configuration:{ demandIntercept:120,supplyIntercept:20,demandSlope:1,supplySlope:1,priceCeiling:0,priceFloor:0,unitTax:0,unitSubsidy:0,policy:'None',buyerCount:10,sellerCount:10,unitsPerBuyer:1,unitsPerSeller:2,maximumRounds:4,scheduledShocks:[] }, maximumRounds:4, roles:roles.map(code => ({code,enabled:true,seePrivateInformation:code !== 'GOVERNMENT',objectives:[]})),enabledActions:[],assessmentDimensions:[] });
export const marketSections = ['Basics','Learning goals','Market configuration','Roles & actions','Objectives','Events / shocks','Student visibility','Teaching prompts','Validate','Preview & publish'];
export function MarketEditor({value,onChange,section}:{value:CompetitiveMarketScenarioContent;onChange(value:CompetitiveMarketScenarioContent):void;section:number}) {
  const set=<K extends keyof CompetitiveMarketScenarioContent>(key:K,next:CompetitiveMarketScenarioContent[K])=>onChange({...value,[key]:next});
  const config=(key:keyof CompetitiveMarketScenarioContent['configuration'],next:number|string|object[])=>set('configuration',{...value.configuration,[key]:next});
  if(section===0)return <div className="form-grid"><TextField id="market-briefing" label="Scenario briefing" value={value.briefing} required multiline onChange={v=>set('briefing',v)}/><NumberField id="market-rounds" label="Maximum rounds" value={value.maximumRounds} min={1} onChange={v=>{set('maximumRounds',v);config('maximumRounds',v)}}/></div>;
  if(section===1)return <LinesField id="market-learning" label="Learning objectives" value={value.learningObjectives} onChange={v=>set('learningObjectives',v)} help="Enter one objective per line."/>;
  if(section===2)return <><div className="form-grid columns-2">{([['demandIntercept','Demand intercept'],['supplyIntercept','Supply intercept'],['demandSlope','Demand slope'],['supplySlope','Supply slope'],['buyerCount','Number of buyers'],['sellerCount','Number of sellers'],['unitsPerBuyer','Units per buyer'],['unitsPerSeller','Units per seller']] as const).map(([key,label])=><NumberField key={key} id={`market-${key}`} label={label} value={value.configuration[key]} onChange={v=>config(key,v)}/>)}</div><div className="form-field"><label htmlFor="market-policy">Market policy</label><select id="market-policy" value={value.configuration.policy} onChange={e=>config('policy',e.target.value as MarketPolicyType)}>{policies.map(x=><option key={x} value={x}>{x.replace(/([A-Z])/g,' $1').trim()}</option>)}</select></div><div className="form-grid columns-2">{([['priceCeiling','Price ceiling'],['priceFloor','Price floor'],['unitTax','Per-unit tax'],['unitSubsidy','Per-unit subsidy']] as const).map(([key,label])=><NumberField key={key} id={`market-${key}`} label={label} value={value.configuration[key]} onChange={v=>config(key,v)}/>)}</div><p className="notice">The backend determines whether policy values are compatible and publishable.</p></>;
  if(section===3)return <><div className="card-grid">{roles.map(code=>{const role=value.roles.find(x=>x.code===code)??{code,enabled:false,seePrivateInformation:false,objectives:[]};const update=(patch:Partial<typeof role>)=>set('roles',[...value.roles.filter(x=>x.code!==code),{...role,...patch}]);return <section className="card" key={code}><Check label={code[0]+code.slice(1).toLowerCase()} checked={role.enabled} onChange={enabled=>update({enabled})}/><LinesField id={`market-role-${code}`} label="Role objectives" value={role.objectives} onChange={objectives=>update({objectives})}/></section>})}</div><h3>Available actions</h3><div className="checks">{actions.map(action=><Check key={action} label={action.replaceAll('_',' ')} checked={(value.enabledActions??[]).includes(action)} onChange={yes=>set('enabledActions',yes?[...(value.enabledActions??[]),action]:(value.enabledActions??[]).filter(x=>x!==action))}/>)}</div></>;
  if(section===4)return <><p className="notice">Economic objectives describe desired simulation outcomes. Assessment dimensions describe conceptual learning evidence.</p><div className="checks">{assessment.map(([id,label])=><Check key={id} label={label} checked={(value.assessmentDimensions??[]).includes(id)} onChange={yes=>set('assessmentDimensions',yes?[...(value.assessmentDimensions??[]),id]:(value.assessmentDimensions??[]).filter(x=>x!==id))}/>)}</div></>;
  if(section===5){const shocks=value.configuration.scheduledShocks??[];return <><div className="section-heading"><h3>Scheduled shocks</h3><button type="button" onClick={()=>config('scheduledShocks',[...shocks,{round:1,type:'demand_increase',intensity:'Mild'}])}>Add shock</button></div>{shocks.map((shock,index)=><div className="repeat-row" key={index}><NumberField id={`market-shock-round-${index}`} label="Round" value={shock.round} min={1} max={value.maximumRounds} onChange={round=>config('scheduledShocks',shocks.map((x,i)=>i===index?{...x,round}:x))}/><label>Shock type<select value={shock.type} onChange={e=>config('scheduledShocks',shocks.map((x,i)=>i===index?{...x,type:e.target.value}:x))}>{['demand_increase','demand_decrease','supply_increase','supply_decrease'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label><label>Intensity<select value={shock.intensity} onChange={e=>config('scheduledShocks',shocks.map((x,i)=>i===index?{...x,intensity:e.target.value as MarketIntensity}:x))}>{intensities.map(x=><option key={x}>{x}</option>)}</select></label><button type="button" className="secondary" onClick={()=>config('scheduledShocks',shocks.filter((_,i)=>i!==index))}>Remove</button></div>)}</>}
  if(section===6)return <><p className="notice"><strong>Private market information:</strong> buyer valuations are hidden from other students; seller costs are role-private. The model generates these values from aggregate configuration and seed—they are not directly authored.</p><div className="checks">{value.roles.map((role,index)=><Check key={role.code} label={`${role.code}: role-private information`} checked={role.seePrivateInformation} help={role.code==='GOVERNMENT'?'Enabling this may reveal normally private information.':undefined} onChange={seePrivateInformation=>set('roles',value.roles.map((x,i)=>i===index?{...x,seePrivateInformation}:x))}/>)}</div></>;
  if(section===7)return <div className="form-grid"><LinesField id="market-discussion" label="Discussion prompts" value={value.discussionPrompts} onChange={v=>set('discussionPrompts',v)}/><LinesField id="market-debrief" label="Debrief prompts" value={value.debriefPrompts} onChange={v=>set('debriefPrompts',v)}/></div>;
  return null;
}
