import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth, useRuntime } from '../../app/runtime';
import { courseService } from '../courses/service';
import { keys } from '../../lib/api/query';
import { AdmissionStatusCard } from './admission';
import { EmptyState, ErrorState, LoadingState } from '../../components/states';
import { getClassroomAdmissionMessage, getSessionAdmissionMessage } from '../../lib/errors/admission';
const norm = (v: string) => v.trim().toLowerCase();

export function StudentHome() {
  const { api } = useRuntime(); const { user } = useAuth(); const navigate = useNavigate(); const qc = useQueryClient();
  const [classCode, setClassCode] = useState(''); const [sessionCode, setSessionCode] = useState('');
  const req = useQuery({ queryKey: keys.myClassroomJoinRequests(user!.id), queryFn: ({ signal }) => courseService(api).myClassroomJoinRequests(signal), refetchOnWindowFocus: true, refetchOnReconnect: true });
  const classes = useQuery({ queryKey: keys.myClassrooms(user!.id), queryFn: ({ signal }) => courseService(api).myClassrooms(signal), refetchOnWindowFocus: true, refetchOnReconnect: true });
  const sreq = useQuery({ queryKey: keys.mySessionJoinRequests(user!.id), queryFn: ({ signal }) => courseService(api).mySessionJoinRequests(signal), refetchOnWindowFocus: true, refetchOnReconnect: true });
  const sessions = useQuery({ queryKey: keys.mySessions(user!.id), queryFn: ({ signal }) => courseService(api).mySessions(signal), refetchOnWindowFocus: true, refetchOnReconnect: true });
  const classroomJoin = useMutation({ mutationFn: () => courseService(api).requestClassroomJoin(classCode.trim()), onSuccess: async () => { setClassCode(''); await Promise.all([qc.invalidateQueries({ queryKey: keys.myClassroomJoinRequests(user!.id) }), qc.invalidateQueries({ queryKey: keys.myClassrooms(user!.id) })]); } });
  const sessionJoin = useMutation({ mutationFn: () => courseService(api).requestSessionJoin(sessionCode.trim()), onSuccess: async r => { await Promise.all([qc.invalidateQueries({ queryKey: keys.mySessionJoinRequests(user!.id) }), qc.invalidateQueries({ queryKey: keys.mySessions(user!.id) })]); if (norm(r.status) === 'approved') navigate(`/simulation/${r.sessionId}`); } });
  const latest = req.data?.[0]; const latestSession = sreq.data?.[0]; const member = classes.data?.find(x => latest && x.classroomId === latest.classroomId); const participant = sessions.data?.find(x => latestSession && x.sessionId === latestSession.sessionId);
  return <><header className="page-heading"><p className="eyebrow">Student workspace</p><h1>Ready for a new perspective?</h1><p>Request classroom access, then open an assigned simulation.</p></header><section className="card"><h2>Join a classroom</h2><p>Enter the code shared by your instructor. Your request must be approved.</p>{req.isPending || classes.isPending ? <LoadingState label="Checking classroom access"/> : member ? <AdmissionStatusCard title="Classroom access" status="Approved">You are a member of {member.name}.</AdmissionStatusCard> : latest && norm(latest.status) === 'pending' ? <AdmissionStatusCard title="Classroom access" status="Pending">Waiting for instructor approval.</AdmissionStatusCard> : latest && norm(latest.status) === 'rejected' ? <AdmissionStatusCard title="Classroom access" status="Rejected">Your request was not approved.</AdmissionStatusCard> : <form className="input-row" onSubmit={e => { e.preventDefault(); if (classCode.trim()) classroomJoin.mutate(); }}><label htmlFor="classroom-code">Classroom code</label><input id="classroom-code" value={classCode} onChange={e => setClassCode(e.target.value.toUpperCase())} required/><button disabled={classroomJoin.isPending}>{classroomJoin.isPending ? 'Sending…' : 'Request to join'}</button></form>}{classroomJoin.error && <p role="alert">{getClassroomAdmissionMessage(classroomJoin.error)}</p>}</section><section className="card"><h2>Join a live session</h2>{sreq.isPending || sessions.isPending ? <LoadingState label="Checking session access"/> : participant ? <AdmissionStatusCard title="Session access" status="Approved">Access approved. <Link to={`/simulation/${participant.sessionId}`}>Open session</Link></AdmissionStatusCard> : latestSession && norm(latestSession.status) === 'pending' ? <AdmissionStatusCard title="Session access" status="Pending">Waiting for instructor approval.</AdmissionStatusCard> : latestSession && norm(latestSession.status) === 'rejected' ? <AdmissionStatusCard title="Session access" status="Rejected">Your request to join this session was not approved.</AdmissionStatusCard> : <form className="input-row" onSubmit={e => { e.preventDefault(); if (sessionCode.trim()) sessionJoin.mutate(); }}><label htmlFor="join-code">Session code</label><input id="join-code" value={sessionCode} onChange={e => setSessionCode(e.target.value.toUpperCase())} required/><button disabled={sessionJoin.isPending}>{sessionJoin.isPending ? 'Sending…' : 'Request to join'}</button></form>}{sessionJoin.error && <p role="alert">{getSessionAdmissionMessage(sessionJoin.error)}</p>}</section><SessionsPage/></>;
}
export function SessionsPage() { const { api } = useRuntime(); const { user } = useAuth(); const q = useQuery({ queryKey: keys.mySessions(user!.id), queryFn: ({ signal }) => courseService(api).mySessions(signal), refetchOnWindowFocus: true, refetchOnReconnect: true }); if (q.isPending) return <LoadingState label="Loading your sessions"/>; if (q.isError) return <ErrorState error={q.error} retry={() => void q.refetch()}/>; return <section><div className="section-heading"><h2>My sessions</h2></div>{q.data.length === 0 ? <EmptyState title="No assigned sessions"><p>Your instructor will add you to a classroom simulation.</p></EmptyState> : <div className="card-grid">{q.data.map(s => <article className="card" key={s.sessionId}><p className="eyebrow">{s.status}</p><h3>{s.scenarioTitle}</h3><p>{s.classroomName} · {s.modelIdentifier}:{s.modelVersion}</p><p>Round {s.currentRound} · {s.currentPhase}</p><Link to={`/simulation/${s.sessionId}`}>Open session</Link></article>)}</div>}</section>; }
