import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useAuth, useRuntime } from '../../app/runtime';
import { courseService } from '../courses/service';
import { keys } from '../../lib/api/query';
import { BackgroundStatus, EmptyState, ErrorState, LoadingState } from '../../components/states';
import type { ClassroomSummary } from '../../types/classrooms';

export function ClassroomListPage() {
  const { api } = useRuntime(); const { user } = useAuth(); const [page, setPage] = useState(1); const q = useQuery({ queryKey: keys.classrooms(user!.id, page, 25), queryFn: ({ signal }) => courseService(api).classrooms(page, 25, signal) });
  if (q.isPending) return <LoadingState label="Loading classrooms"/>; if (q.isError) return <ErrorState error={q.error} retry={() => void q.refetch()}/>;
  return <><header className="page-heading"><p className="eyebrow">Instructor workspace</p><h1>Classrooms</h1><p>Manage the real classrooms provisioned for your courses.</p></header>{q.data.items.length === 0 ? <EmptyState title="No classrooms"><p>Create a classroom through the platform provisioning workflow.</p></EmptyState> : <><div className="card-grid">{q.data.items.map(c => <ClassroomCard key={c.classroomId} classroom={c}/>)}</div><Pagination page={q.data.page} pageSize={q.data.pageSize} total={q.data.totalCount} onPage={setPage}/></>}</>;
}
function ClassroomCard({ classroom }: { classroom: ClassroomSummary }) { return <article className="card"><p className="eyebrow">{classroom.courseCode}</p><h2>{classroom.name}</h2><p>{classroom.courseName}</p><Link to={`/instructor/classrooms/${classroom.classroomId}`}>Open classroom</Link></article>; }
export function ClassroomDetailPage() {
  const { api } = useRuntime(); const { user } = useAuth(); const { classroomId = '' } = useParams(); const q = useQuery({ queryKey: keys.classroom(user!.id, classroomId), queryFn: ({ signal }) => courseService(api).classroom(classroomId, signal) }); const roster = useQuery({ queryKey: keys.roster(user!.id, classroomId), queryFn: ({ signal }) => courseService(api).roster(classroomId, signal), enabled: !!q.data }); const sessions = useQuery({ queryKey: keys.sessionLists(user!.id, 1, 25, classroomId, '', ''), queryFn: ({ signal }) => courseService(api).sessions({ classroomId, page: 1, pageSize: 25 }, signal), enabled: !!q.data });
  if (q.isPending) return <LoadingState label="Loading classroom"/>; if (q.isError) return <ErrorState error={q.error} retry={() => void q.refetch()}/>;
  return <><header className="page-heading"><p className="eyebrow">Classroom</p><h1>{q.data.name}</h1><p>{q.data.courseName} · {q.data.courseCode}</p><Link className="button-link" to="/instructor/scenarios">Choose a published scenario</Link></header><section><div className="section-heading"><h2>Roster</h2><BackgroundStatus active={roster.isFetching}/></div>{roster.isPending ? <LoadingState label="Loading roster"/> : roster.isError ? <ErrorState error={roster.error} retry={() => void roster.refetch()}/> : roster.data.length === 0 ? <EmptyState title="No enrolled students"><p>The backend returned an empty roster.</p></EmptyState> : <div className="card-grid">{roster.data.map(s => <article className="card" key={s.participantUserId}><h3>{s.userName || s.email || s.participantUserId}</h3><p>{s.email}</p><p className="muted">Enrolled {new Date(s.enrolledAt).toLocaleDateString()}</p></article>)}</div>}</section><section><div className="section-heading"><h2>Simulation sessions</h2></div>{sessions.isPending ? <LoadingState label="Loading sessions"/> : sessions.isError ? <ErrorState error={sessions.error} retry={() => void sessions.refetch()}/> : sessions.data.items.length === 0 ? <EmptyState title="No sessions"><p>Launch a published scenario to create the first session.</p></EmptyState> : <div className="card-grid">{sessions.data.items.map(s => <article className="card" key={s.sessionId}><p className="eyebrow">{s.status}</p><h3>{s.scenarioTitle}</h3><p>{s.modelIdentifier}:{s.modelVersion} · {s.currentPhase} · Round {s.currentRound}</p><Link to={s.status === 'Draft' ? `/instructor/sessions/${s.sessionId}/setup` : `/simulation/${s.sessionId}`}>{s.status === 'Draft' ? 'Open setup' : 'Open runtime'}</Link></article>)}</div>}</section></>;
}
export function Pagination({ page, pageSize, total, onPage }: { page: number; pageSize: number; total: number; onPage: (page: number) => void }) { const max = Math.max(1, Math.ceil(total / pageSize)); return <nav className="button-row" aria-label="Pagination"><button className="secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><span>Page {page} of {max}</span><button className="secondary" disabled={page >= max} onClick={() => onPage(page + 1)}>Next</button></nav>; }
