import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth, useRuntime } from '../../app/runtime';
import { courseService } from '../courses/service';
import { keys } from '../../lib/api/query';
import { ErrorState, LoadingState } from '../../components/states';
import { Pagination } from './classrooms';

export function InstructorSessionsPage() {
  const {api}=useRuntime(); const {user}=useAuth(); const [page,setPage]=useState(1); const q=useQuery({queryKey:keys.sessionLists(user!.id,page,25,'','',''),queryFn:({signal})=>courseService(api).sessions({page,pageSize:25},signal)});
  if(q.isPending)return <LoadingState label="Loading sessions"/>; if(q.isError)return <ErrorState error={q.error} retry={()=>void q.refetch()}/>;
  return <><header className="page-heading"><h1>Sessions</h1></header><div className="card-grid">{q.data.items.map(s=><article className="card" key={s.sessionId}><p>{s.status}</p><h2>{s.scenarioTitle}</h2><p>{s.classroomName} · {s.modelIdentifier}:{s.modelVersion}</p><p>Round {s.currentRound} · {s.currentPhase}</p><Link to={s.status==='Draft'?`/instructor/sessions/${s.sessionId}/setup`:`/simulation/${s.sessionId}`}>Open</Link></article>)}</div><Pagination page={q.data.page} pageSize={q.data.pageSize} total={q.data.totalCount} onPage={setPage}/></>;
}

export function SessionSetupPage() {
  const {api}=useRuntime(); const {user}=useAuth(); const {sessionId=''}=useParams(); const qc=useQueryClient(); const service=courseService(api); const setup=useQuery({queryKey:keys.setup(user!.id,sessionId),queryFn:({signal})=>service.setup(sessionId,signal)}); const join=useQuery({queryKey:['session',user!.id,sessionId,'join-code'],queryFn:({signal})=>service.joinCode(sessionId,signal),enabled:!!sessionId,refetchOnWindowFocus:true}); const [teamName,setTeamName]=useState(''); const [member,setMember]=useState('');
  const refresh=()=>void qc.invalidateQueries({queryKey:keys.setup(user!.id,sessionId)}); const team=useMutation({mutationFn:()=>service.createTeam(sessionId,teamName.trim()),onSuccess:()=>{setTeamName('');refresh();}}); const add=useMutation({mutationFn:({teamId,userId}:{teamId:string;userId:string})=>service.addMember(sessionId,teamId,userId),onSuccess:refresh}); const start=useMutation({mutationFn:()=>service.startSession(sessionId),onSuccess:()=>window.location.assign(`/simulation/${sessionId}`)});
  if(setup.isPending)return <LoadingState label="Recovering session setup"/>; if(setup.isError)return <ErrorState error={setup.error} retry={()=>void setup.refetch()}/>; const d=setup.data; const assigned=new Set(d.teams.flatMap(t=>t.members));
  return <><header className="page-heading"><p className="eyebrow">Instructor lobby</p><h1>{d.scenario.title}</h1><p>{d.classroom.name} · {d.model.identifier}:{d.model.version}</p></header><section className="card lobby-code"><p className="eyebrow">Join code</p>{join.isPending?<p role="status">Loading join code…</p>:join.isError?<><p>Join code unavailable.</p><button className="secondary" onClick={()=>void join.refetch()}>Retry</button></>:join.data?.active?<><p className="join-code" aria-label="Session join code">{join.data.joinCode}</p><button className="secondary" onClick={()=>void navigator.clipboard?.writeText(join.data.joinCode)}>Copy code</button></>:<p>This session is closed to new participants.</p>}</section><section className="card"><h2>Session</h2><p>Status: {d.session.status} · Round {d.session.currentRound} · {d.session.currentPhase}</p></section><section><h2>Teams</h2><form className="input-row" onSubmit={e=>{e.preventDefault();if(teamName.trim())team.mutate();}}><label htmlFor="team-name">New team</label><input id="team-name" value={teamName} onChange={e=>setTeamName(e.target.value)} required/><button disabled={team.isPending}>Create team</button></form><div className="card-grid">{d.teams.map(t=><article className="card" key={t.teamId}><h3>{t.name}</h3><p>{t.members.length} joined participant{t.members.length===1?'':'s'}</p><label htmlFor={`member-${t.teamId}`}>Assign participant</label><select id={`member-${t.teamId}`} value={member} onChange={e=>setMember(e.target.value)}><option value="">Select</option>{d.participants.filter(p=>!assigned.has(p.userId)).map(p=><option key={p.userId} value={p.userId}>{p.userId}</option>)}</select><button className="secondary" disabled={!member||add.isPending} onClick={()=>{add.mutate({teamId:t.teamId,userId:member});setMember('');}}>Assign</button></article>)}</div></section><section className="card"><h2>Readiness &amp; start</h2>{d.readiness.blockers.length>0&&<ul>{d.readiness.blockers.map((b,i)=><li key={i}>{b.code}</li>)}</ul>}<button disabled={!d.readiness.isReady||start.isPending} onClick={()=>start.mutate()}>{start.isPending?'Starting…':'Start session'}</button>{(team.error||add.error||start.error)&&<ErrorState error={team.error||add.error||start.error}/>}</section></>;
}
