import type { MacroScenarioContent, PolicyIntensity } from '../../types/short-run-macro';
import { Check, LinesField, NumberField, TextField } from '../scenarios/fields';

const roles = ['GOVERNMENT', 'CENTRAL_BANK', 'BUSINESS', 'HOUSEHOLD_LABOR'] as const;
const roleNames: Record<string, string> = { GOVERNMENT: 'Government', CENTRAL_BANK: 'Central Bank', BUSINESS: 'Business', HOUSEHOLD_LABOR: 'Household / Labor' };
const actions = ['SET_FISCAL_POLICY', 'SET_MONETARY_POLICY', 'SET_BUSINESS_STRATEGY', 'SET_HOUSEHOLD_LABOR_STANCE'] as const;
const intensities: PolicyIntensity[] = ['Mild', 'Moderate', 'Strong'];
const shocks = ['demand_slump', 'demand_boom', 'supply_disruption', 'productivity_boost', 'confidence_crisis'] as const;
const assessment = [[0, 'Directional prediction'], [1, 'Causal mechanism'], [2, 'Trade-off awareness'], [3, 'Lag recognition'], [4, 'Objective achievement'], [5, 'Policy reasoning'], [6, 'Economic outcome']] as const;

export const blankMacro = (): MacroScenarioContent => ({ briefing: '', learningObjectives: [], discussionPrompts: [], debriefPrompts: [], startingConditions: { outputIndex: 100, potentialOutputIndex: 100, inflation: 2, unemployment: 5, policyRate: 3, debtToOutput: 55 }, maximumQuarters: 4, roles: roles.map(code => ({ code, enabled: true, canSeeInstitutionalIndicators: false, objectives: [] })), enabledActions: [], allowedIntensities: [], scheduledShocks: [], teamObjectives: { inflationMinimum: 1, inflationMaximum: 3, unemploymentMaximum: 6, outputGapAbsoluteMaximum: 2, debtToOutputMaximum: 80 }, assessmentDimensions: [] });

export const macroSections = ['Basics', 'Learning goals', 'Starting conditions', 'Roles & actions', 'Objectives', 'Events / shocks', 'Student visibility', 'Teaching prompts', 'Validate', 'Preview & publish'];
export function MacroEditor({ value, onChange, section }: { value: MacroScenarioContent; onChange(value: MacroScenarioContent): void; section: number }) {
  const set = <K extends keyof MacroScenarioContent>(key: K, next: MacroScenarioContent[K]) => onChange({ ...value, [key]: next });
  const start = (key: keyof MacroScenarioContent['startingConditions'], next: number) => set('startingConditions', { ...value.startingConditions, [key]: next });
  if (section === 0) return <div className="form-grid"><TextField id="macro-briefing" label="Scenario briefing" value={value.briefing} required multiline onChange={v => set('briefing', v)}/><NumberField id="macro-quarters" label="Maximum quarters" value={value.maximumQuarters} min={1} max={20} onChange={v => set('maximumQuarters', v)} help="The backend accepts 1–20 quarters."/></div>;
  if (section === 1) return <LinesField id="macro-learning" label="Learning objectives" value={value.learningObjectives} onChange={v => set('learningObjectives', v)} help="Enter one objective per line."/>;
  if (section === 2) { const bounds = { outputIndex:[50,200], potentialOutputIndex:[50,200], inflation:[-3,20], unemployment:[1.5,25], policyRate:[0,20], debtToOutput:[0,200] } as const; return <div className="form-grid columns-2">{([['outputIndex','Output index'],['potentialOutputIndex','Potential output index'],['inflation','Inflation'],['unemployment','Unemployment'],['policyRate','Policy rate'],['debtToOutput','Debt-to-output']] as const).map(([key,label]) => <NumberField key={key} id={`macro-${key}`} label={label} value={value.startingConditions[key]} min={bounds[key][0]} max={bounds[key][1]} onChange={v => start(key,v)}/>)}</div>; }
  if (section === 3) return <><h3>Roles</h3><div className="card-grid">{roles.map(code => { const role = value.roles.find(x => x.code === code) ?? { code, enabled: false, canSeeInstitutionalIndicators: false, objectives: [] }; const update = (patch: Partial<typeof role>) => set('roles', [...value.roles.filter(x => x.code !== code), { ...role, ...patch }]); return <section className="card" key={code}><Check label={roleNames[code]} checked={role.enabled} onChange={enabled => update({enabled})}/><LinesField id={`macro-role-${code}`} label="Role objectives" value={role.objectives} onChange={objectives => update({objectives})}/></section>; })}</div><h3>Available actions</h3><div className="checks">{actions.map(action => <Check key={action} label={action.replaceAll('_',' ')} checked={value.enabledActions.includes(action)} onChange={yes => set('enabledActions', yes ? [...value.enabledActions, action] : value.enabledActions.filter(x => x !== action))}/>)}</div><h3>Allowed intensities</h3><div className="checks">{intensities.map(intensity => <Check key={intensity} label={intensity} checked={value.allowedIntensities.includes(intensity)} onChange={yes => set('allowedIntensities', yes ? [...value.allowedIntensities, intensity] : value.allowedIntensities.filter(x => x !== intensity))}/>)}</div></>;
  if (section === 4) { const o = value.teamObjectives; const update = (key: keyof typeof o, next: number) => set('teamObjectives', {...o,[key]:next}); return <><p className="notice">Economic objectives describe desired simulation outcomes. They are not conceptual assessment scores.</p><div className="form-grid columns-2">{([['inflationMinimum','Minimum inflation'],['inflationMaximum','Maximum inflation'],['unemploymentMaximum','Maximum unemployment'],['outputGapAbsoluteMaximum','Maximum absolute output gap'],['debtToOutputMaximum','Maximum debt-to-output']] as const).map(([key,label]) => <NumberField key={key} id={`macro-objective-${key}`} label={label} value={o[key]} onChange={v => update(key,v)}/>)}</div><h3>Assessment dimensions</h3><div className="checks">{assessment.map(([id,label]) => <Check key={id} label={label} checked={(value.assessmentDimensions ?? []).includes(id)} onChange={yes => set('assessmentDimensions', yes ? [...(value.assessmentDimensions ?? []), id] : (value.assessmentDimensions ?? []).filter(x => x !== id))}/>)}</div></>; }
  if (section === 5) return <><div className="section-heading"><h3>Scheduled shocks</h3><button type="button" onClick={() => set('scheduledShocks', [...value.scheduledShocks, { round: 1, type: shocks[0], intensity: 'Mild' }])}>Add shock</button></div>{value.scheduledShocks.length === 0 ? <p className="muted">No scheduled shocks.</p> : value.scheduledShocks.map((shock,index) => <div className="repeat-row" key={index}><NumberField id={`macro-shock-round-${index}`} label="Quarter" value={shock.round} min={1} max={value.maximumQuarters} onChange={round => set('scheduledShocks', value.scheduledShocks.map((x,i) => i === index ? {...x,round} : x))}/><label htmlFor={`macro-shock-type-${index}`}>Shock type<select id={`macro-shock-type-${index}`} value={shock.type} onChange={e => set('scheduledShocks', value.scheduledShocks.map((x,i) => i === index ? {...x,type:e.target.value} : x))}>{shocks.map(x => <option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label>Intensity<select value={shock.intensity} onChange={e => set('scheduledShocks', value.scheduledShocks.map((x,i) => i === index ? {...x,intensity:e.target.value as PolicyIntensity} : x))}>{intensities.map(x => <option key={x}>{x}</option>)}</select></label><button type="button" className="secondary" onClick={() => set('scheduledShocks', value.scheduledShocks.filter((_,i) => i !== index))}>Remove</button></div>)}</>;
  if (section === 6) return <><p>Institutional indicators are role-visible only when enabled. Model internals remain instructor-only.</p><div className="checks">{value.roles.map((role,index) => <Check key={role.code} label={`${roleNames[role.code] ?? role.code}: institutional indicators`} checked={role.canSeeInstitutionalIndicators} onChange={canSeeInstitutionalIndicators => set('roles', value.roles.map((x,i) => i === index ? {...x,canSeeInstitutionalIndicators} : x))}/>)}</div></>;
  if (section === 7) return <div className="form-grid"><LinesField id="macro-discussion" label="Discussion prompts" value={value.discussionPrompts} onChange={v => set('discussionPrompts',v)}/><LinesField id="macro-debrief" label="Debrief prompts" value={value.debriefPrompts} onChange={v => set('debriefPrompts',v)}/></div>;
  return null;
}
