import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useAuth, useRuntime } from '../../app/runtime';
import { BackgroundStatus, ErrorState, LoadingState } from '../../components/states';
import { keys } from '../../lib/api/query';
import type { SaveResult } from '../../lib/api/concurrency';
import type { MacroDraft, MacroPreviewResult, MacroScenarioContent } from '../../types/short-run-macro';
import type { CompetitiveMarketDraft, CompetitiveMarketScenarioContent, MarketPreviewResult } from '../../types/competitive-market';
import type { ValidationReport } from '../../types/scenarios';
import { MacroEditor, macroSections } from '../short-run-macro/authoring';
import { MarketEditor, marketSections } from '../competitive-market/authoring';
import { macroAuthoring, marketAuthoring, type EditDraft } from './service';
import { TextField } from './fields';

type Model = 'macro'|'market';
type AnyDraft = MacroDraft|CompetitiveMarketDraft;
type AnyContent = MacroScenarioContent|CompetitiveMarketScenarioContent;
function useLeaveWarning(dirty:boolean){useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};const links=(event:MouseEvent)=>{if(!dirty||event.defaultPrevented||event.button!==0)return;const anchor=(event.target as Element).closest('a[href]') as HTMLAnchorElement|null;if(!anchor||anchor.target==='_blank')return;if(!window.confirm('You have unsaved scenario changes. Leave without saving?'))event.preventDefault();};window.addEventListener('beforeunload',warn);document.addEventListener('click',links);return()=>{window.removeEventListener('beforeunload',warn);document.removeEventListener('click',links)}},[dirty]);}
const issueSection=(code:string,sections:string[])=>{const c=code.toLowerCase();const wanted=c.includes('shock')?'Events / shocks':c.includes('role')||c.includes('action')?'Roles & actions':c.includes('objective')?'Objectives':c.includes('brief')||c.includes('prompt')?'Teaching prompts':c.includes('starting')||c.includes('bound')?'Starting conditions':null;return wanted?sections.indexOf(wanted):-1};

export function ScenarioEditorPage(){
  const {model,draftId}=useParams(); const selected:Model=model==='macro'?'macro':model==='market'?'market':null as never; const {api,queries}=useRuntime();const {user}=useAuth();const navigate=useNavigate();
  if(!selected||!draftId)return <ErrorState error={new Error('Unknown scenario model or missing draft ID.')}/>;
  const service=selected==='macro'?macroAuthoring(api):marketAuthoring(api); const key=keys.scenario(user!.id,selected,draftId);
  const query=useQuery({queryKey:key,queryFn:({signal})=>service.get(draftId,signal) as Promise<AnyDraft>});
  const [name,setName]=useState('');const [content,setContent]=useState<AnyContent|null>(null);const [dirty,setDirty]=useState(false);const [section,setSection]=useState(0);const [saveState,setSaveState]=useState<'saved'|'unsaved'|'saving'|'failed'|'conflict'>('saved');const [conflict,setConflict]=useState<AnyDraft|null>(null);const [validation,setValidation]=useState<ValidationReport|null>(null);const [preview,setPreview]=useState<MacroPreviewResult|MarketPreviewResult|null>(null);const [publishedId,setPublishedId]=useState<string|null>(null);
  const sections=selected==='macro'?macroSections:marketSections;const immutable=publishedId!==null||query.data?.document.status==='Published'||query.data?.document.status==='Archived';
  useEffect(()=>{if(query.data&&!content){setName(query.data.document.name);setContent(structuredClone(query.data.content));}},[query.data,content]);useLeaveWarning(dirty);
  const save=useMutation({mutationFn:async()=>{if(!query.data||!content)throw new Error('Draft is not loaded.');return service.save(draftId,query.data as never,{name,content} as never) as Promise<SaveResult<AnyDraft,EditDraft<AnyContent>>>},onMutate:()=>setSaveState('saving'),onSuccess:result=>{if(result.kind==='conflict'){setSaveState('conflict');setConflict(result.authoritative);return;}queries.setQueryData(key,result.resource);setDirty(false);setSaveState('saved');setValidation(null)},onError:()=>setSaveState('failed')});
  const validate=useMutation({mutationFn:()=>service.validate(draftId),onSuccess:setValidation});
  const previewMutation=useMutation({mutationFn:()=>selected==='macro'?macroAuthoring(api).preview<MacroPreviewResult>(draftId,{seed:1}):marketAuthoring(api).preview<MarketPreviewResult>(draftId,{seed:1}),onSuccess:setPreview});
  const publish=useMutation({mutationFn:()=>service.publish(draftId,{expectedVersion:query.data!.document.version}),onSuccess:r=>setPublishedId(r.scenarioVersionId)});
  const archive=useMutation({mutationFn:()=>service.archive(draftId,{expectedVersion:query.data!.document.version}),onSuccess:()=>void queries.invalidateQueries({queryKey:key})});
  const clone=useMutation({mutationFn:(cloneName:string)=>service.clone(service.prepareClone(draftId,cloneName) as never) as Promise<AnyDraft>,onSuccess:d=>navigate(`/instructor/scenarios/${selected}/${d.document.id}`)});
  const change=(next:AnyContent)=>{setContent(next);setDirty(true);setSaveState('unsaved');setValidation(null)};
  if(query.isPending||!content)return <LoadingState label="Loading scenario draft"/>;if(query.isError)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;
  const lifecycle=query.data.document.status;
  return <><header className="page-heading"><p className="eyebrow">{selected==='macro'?'Short-Run Macroeconomics':'Competitive Market'} · {lifecycle}</p><div className="editor-title"><h1>{name||'Untitled scenario'}</h1><span className={`save-state ${saveState}`} role="status">{saveState==='saved'?'Saved':saveState==='unsaved'?'Unsaved changes':saveState==='saving'?'Saving…':saveState==='conflict'?'Conflict detected':'Save failed'}</span></div><p>Draft version {query.data.document.version} · Updated {new Date(query.data.document.updatedAt).toLocaleString()}</p></header>
    {immutable&&<section className="notice"><h2>{lifecycle==='Archived'?'Archived scenario':'Published version is immutable'}</h2><p>This version cannot be edited. Clone it to continue authoring without changing frozen or historical sessions.</p></section>}
    <div className="authoring-layout"><nav className="step-nav" aria-label="Scenario editor sections">{sections.map((label,index)=><button type="button" className={index===section?'active secondary':'secondary'} aria-current={index===section?'step':undefined} onClick={()=>setSection(index)} key={label}><span>{index+1}</span>{label}</button>)}</nav><section className="editor-panel" aria-labelledby="section-heading"><div className="section-heading"><h2 id="section-heading">{sections[section]}</h2><BackgroundStatus active={query.isFetching}/></div><fieldset disabled={immutable}>
      {section===0&&<TextField id="scenario-name" label="Scenario title" value={name} required onChange={v=>{setName(v);setDirty(true);setSaveState('unsaved')}}/>}
      {selected==='macro'?<MacroEditor value={content as MacroScenarioContent} onChange={change} section={section}/>:<MarketEditor value={content as CompetitiveMarketScenarioContent} onChange={change} section={section}/>} 
      {section===8&&<ValidationPanel report={validation} pending={validate.isPending} error={validate.error} sections={sections} go={setSection} run={()=>validate.mutate()}/>} 
      {section===9&&<PreviewPublish preview={preview} validation={validation} dirty={dirty} pending={previewMutation.isPending||publish.isPending} error={previewMutation.error||publish.error} runPreview={()=>previewMutation.mutate()} publish={()=>{if(window.confirm('Publish this saved scenario as an immutable version?'))publish.mutate()}} publishedId={publishedId}/>} 
    </fieldset><div className="editor-actions"><button type="button" disabled={immutable||!dirty||save.isPending} onClick={()=>save.mutate()}>Save changes</button><button type="button" className="secondary" onClick={()=>{const next=window.prompt('Name for the cloned draft',`${name} copy`);if(next)clone.mutate(next)}}>Clone</button><button type="button" className="danger" disabled={immutable} onClick={()=>{if(window.confirm('Archive this scenario? Existing frozen sessions and history are not changed.'))archive.mutate()}}>Archive</button><Link to="/instructor/scenarios">Back to scenarios</Link></div>{save.error&&<ErrorState error={save.error}/>} {archive.error&&<ErrorState error={archive.error}/>} {clone.error&&<ErrorState error={clone.error}/>} {conflict&&<section className="state error" role="alert"><h2>Scenario changed elsewhere</h2><p>Your unsaved input is still in this editor. The server now has version {conflict.document.version}. Review your work and reload when you are ready; it was not overwritten.</p><button type="button" className="secondary" onClick={()=>{setContent(null);setConflict(null);setDirty(false);void query.refetch()}}>Load server version</button></section>}</section></div></>;
}
function ValidationPanel({report,pending,error,sections,go,run}:{report:ValidationReport|null;pending:boolean;error:unknown;sections:string[];go(n:number):void;run():void}){return <div><p>Readiness is calculated by the backend. Blockers prevent publication; warnings do not unless the backend says otherwise.</p><button type="button" disabled={pending} onClick={run}>{pending?'Validating…':'Validate scenario'}</button>{error ? <ErrorState error={error}/> : null} {report&&<section className="validation-report" aria-live="polite"><h3>Scenario validation</h3><p><strong>{report.blockers.length} blockers</strong> · {report.warnings.length} warnings</p>{(['blockers','warnings'] as const).map(kind=><div key={kind}><h4>{kind==='blockers'?'Blockers':'Warnings'}</h4>{report[kind].length===0?<p className="muted">None.</p>:<ul>{report[kind].map((issue,index)=>{const target=issueSection(issue.code,sections);return <li key={`${issue.code}-${index}`}><strong>{issue.code}</strong>: {issue.message}{target>=0&&<button type="button" className="text-button" onClick={()=>go(target)}>Go to {sections[target]}</button>}</li>})}</ul>}</div>)}</section>}</div>}
function PreviewPublish({preview,validation,dirty,pending,error,runPreview,publish,publishedId}:{preview:MacroPreviewResult|MarketPreviewResult|null;validation:ValidationReport|null;dirty:boolean;pending:boolean;error:unknown;runPreview():void;publish():void;publishedId:string|null}){const frames=preview&&('quarters'in preview?preview.quarters:preview.rounds);return <div><p>Preview is a deterministic backend diagnostic, not a prediction of student behavior.</p><div className="button-row"><button type="button" className="secondary" disabled={dirty||pending} onClick={runPreview}>Run deterministic preview</button><button type="button" disabled={dirty||pending||!validation?.canPublish||validation.blockers.length>0} onClick={publish}>Publish immutable version</button></div>{dirty&&<p className="notice">Save changes before previewing or publishing.</p>}{!validation&&<p className="muted">Validate the saved draft before publishing.</p>}{error ? <ErrorState error={error}/> : null} {preview&&<section className="preview"><h3>Preview result</h3><p>{frames?.length??0} simulated {'quarters'in preview?'quarters':'rounds'} using backend seed {preview.seed}.</p><PreviewTrajectory preview={preview}/><h4>Diagnostics</h4>{preview.diagnostics.length?<ul>{preview.diagnostics.map((x,i)=><li key={`${x.code}-${i}`}><strong>{x.code}</strong>: {x.message}</li>)}</ul>:<p>No diagnostics returned.</p>}</section>}{publishedId&&<section className="notice" role="status"><h3>Published</h3><p>Immutable scenario version: <code>{publishedId}</code></p></section>}</div>}
function PreviewTrajectory({preview}:{preview:MacroPreviewResult|MarketPreviewResult}){if('quarters'in preview)return <div className="table-scroll"><table><caption>Backend-generated macro trajectory</caption><thead><tr><th>Quarter</th><th>Output</th><th>Inflation</th><th>Unemployment</th><th>Policy rate</th><th>Debt/output</th></tr></thead><tbody>{preview.quarters.map(frame=><tr key={frame.quarter}><th>{frame.quarter}</th><td>{frame.state.outputIndex}</td><td>{frame.state.inflation}</td><td>{frame.state.unemployment}</td><td>{frame.state.policyRate}</td><td>{frame.state.debtToOutput}</td></tr>)}</tbody></table></div>;return <div className="table-scroll"><table><caption>Backend-generated market preview</caption><thead><tr><th>Round</th><th>Price</th><th>Quantity</th><th>Unmatched demand</th><th>Unmatched supply</th><th>Total surplus</th><th>Deadweight loss</th></tr></thead><tbody>{preview.rounds.map(frame=><tr key={frame.round}><th>{frame.round}</th><td>{frame.price}</td><td>{frame.quantityExchanged}</td><td>{frame.unmatchedDemand}</td><td>{frame.unmatchedSupply}</td><td>{frame.totalSurplus}</td><td>{frame.deadweightLoss}</td></tr>)}</tbody></table></div>}
