import { useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth, useRuntime } from '../../app/runtime';
import { BackgroundStatus, EmptyState, ErrorState, LoadingState } from '../../components/states';
import { keys } from '../../lib/api/query';
import type { SimulationModelDescriptor } from '../../types/platform';
import type { MacroScenarioContent } from '../../types/short-run-macro';
import type { CompetitiveMarketScenarioContent } from '../../types/competitive-market';
import { blankMacro } from '../short-run-macro/authoring';
import { blankMarket } from '../competitive-market/authoring';
import { macroAuthoring, marketAuthoring } from './service';

type Model='macro'|'market';
const supported=(identifier:string):Model|null=>identifier==='Economics.ShortRunMacro'?'macro':identifier==='Economics.CompetitiveMarket'?'market':null;
export function ScenarioLibraryPage(){const{api}=useRuntime();const{user}=useAuth();const navigate=useNavigate();const[filter,setFilter]=useState<'all'|Model>('all');const[openModel,setOpenModel]=useState<Model>('macro');const models=useQuery({queryKey:keys.models,queryFn:({signal})=>api.json<SimulationModelDescriptor[]>('/api/v1/models',{anonymous:true,signal})});const macro=useQuery({queryKey:['user',user!.id,'templates','macro'],queryFn:({signal})=>macroAuthoring(api).templates(signal)});const market=useQuery({queryKey:['user',user!.id,'templates','market'],queryFn:({signal})=>marketAuthoring(api).templates(signal)});
  function open(event:FormEvent<HTMLFormElement>){event.preventDefault();const id=String(new FormData(event.currentTarget).get('draftId'));if(id)navigate(`/instructor/scenarios/${openModel}/${encodeURIComponent(id)}`)}
  return <><header className="page-heading"><p className="eyebrow">Instructor workspace</p><h1>Scenario authoring</h1><p>Create from a server template or open an owned draft by ID.</p><Link className="button-link" to="/instructor/scenarios/create">Create scenario</Link></header><section className="notice"><h2>Scenario library availability</h2><p>The backend does not provide scenario or draft discovery. Draft, Published, and Archived collections cannot be truthfully populated. Use a known owned draft ID; published versions remain immutable and are returned only by the publish operation.</p></section><section className="card"><h2>Open an owned draft</h2><form className="input-row" onSubmit={open}><label className="sr-only" htmlFor="open-model">Model</label><select id="open-model" value={openModel} onChange={e=>setOpenModel(e.target.value as Model)}><option value="macro">Short-Run Macro</option><option value="market">Competitive Market</option></select><label className="sr-only" htmlFor="draft-id">Draft ID</label><input id="draft-id" name="draftId" required placeholder="Draft ID"/><button>Open draft</button></form></section><section><div className="section-heading"><h2>Templates</h2><div><label htmlFor="model-filter">Model filter </label><select id="model-filter" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">All models</option><option value="macro">ShortRunMacro</option><option value="market">CompetitiveMarket</option></select></div></div>{models.isPending?<LoadingState label="Loading models"/>:models.isError?<ErrorState error={models.error}/>:models.data.filter(x=>supported(x.identifier)).length===0?<EmptyState title="No supported models"><p>The backend returned no supported authoring models.</p></EmptyState>:<div className="template-groups">{filter!=='market'&&<TemplateGroup title="Short-Run Macroeconomics" query={macro} model="macro"/>}{filter!=='macro'&&<TemplateGroup title="Competitive Market" query={market} model="market"/>}</div>}</section></>}
function TemplateGroup({title,query,model}:{title:string;query:ReturnType<typeof useQuery<any[]>>;model:Model}){return <section><div className="section-heading"><h3>{title}</h3><BackgroundStatus active={query.isFetching}/></div>{query.isPending?<LoadingState label="Loading templates"/>:query.isError?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:query.data!.length===0?<EmptyState title="No templates"/>:<div className="card-grid">{query.data!.map(template=><article className="card" key={template.code}><p className="eyebrow">{template.code}</p><h3>{template.name}</h3>{template.description&&<p>{template.description}</p>}<p>{template.content.briefing}</p><Link to={`/instructor/scenarios/create?model=${model}&template=${encodeURIComponent(template.code)}`}>Use this template</Link></article>)}</div>}</section>}

export function CreateScenarioPage(){const{api}=useRuntime();const navigate=useNavigate();const params=new URLSearchParams(location.search);const initial=params.get('model')==='market'?'market':'macro';const[model,setModel]=useState<Model>(initial);const[name,setName]=useState('');const[definitionId,setDefinitionId]=useState('');const[templateCode,setTemplateCode]=useState(params.get('template')??'');const models=useQuery({queryKey:keys.models,queryFn:({signal})=>api.json<SimulationModelDescriptor[]>('/api/v1/models',{anonymous:true,signal})});const macroTemplates=useQuery({queryKey:['create-templates','macro'],queryFn:({signal})=>macroAuthoring(api).templates(signal)});const marketTemplates=useQuery({queryKey:['create-templates','market'],queryFn:({signal})=>marketAuthoring(api).templates(signal)});const templates=model==='macro'?macroTemplates:marketTemplates;
  const create=useMutation({mutationFn:async()=>{const template=templates.data?.find(x=>x.code===templateCode);const content=(template?.content??(model==='macro'?blankMacro():blankMarket())) as MacroScenarioContent|CompetitiveMarketScenarioContent;if(model==='macro'){const service=macroAuthoring(api);return {model,draft:await service.create(service.prepareCreate({simulationDefinitionId:definitionId,name,content:content as MacroScenarioContent}))}}const service=marketAuthoring(api);return {model,draft:await service.create(service.prepareCreate({simulationDefinitionId:definitionId,name,content:content as CompetitiveMarketScenarioContent}))}},onSuccess:r=>navigate(`/instructor/scenarios/${r.model}/${r.draft.document.id}`)});
  if(models.isPending)return <LoadingState label="Loading simulation models"/>;if(models.isError)return <ErrorState error={models.error}/>;const available=models.data.map(x=>({descriptor:x,model:supported(x.identifier)})).filter(x=>x.model);
  return <><header className="page-heading"><p className="eyebrow">Scenario authoring</p><h1>Create scenario</h1><p>Select an implemented backend model and a server template or blank draft.</p></header><form className="card form-grid" onSubmit={e=>{e.preventDefault();create.mutate()}}><div className="form-field"><label htmlFor="create-model">Simulation model</label><select id="create-model" value={model} onChange={e=>{setModel(e.target.value as Model);setTemplateCode('')}}>{available.map(({descriptor,model})=><option key={`${descriptor.identifier}:${descriptor.version}`} value={model!}>{descriptor.name} · {descriptor.version}</option>)}</select></div><div className="form-field"><label htmlFor="definition-id">Simulation definition ID</label><div className="field-help" id="definition-help">Required because the backend has no definition discovery endpoint.</div><input id="definition-id" value={definitionId} required aria-describedby="definition-help" onChange={e=>setDefinitionId(e.target.value)}/></div><div className="form-field"><label htmlFor="create-name">Scenario title</label><input id="create-name" value={name} required onChange={e=>setName(e.target.value)}/></div><div className="form-field"><label htmlFor="create-template">Starting point</label><select id="create-template" value={templateCode} onChange={e=>setTemplateCode(e.target.value)}><option value="">Blank scenario</option>{templates.data?.map(x=><option value={x.code} key={x.code}>{x.name}</option>)}</select></div><div className="button-row"><button disabled={create.isPending}>{create.isPending?'Creating…':'Create draft'}</button><Link to="/instructor/scenarios">Cancel</Link></div>{create.error&&<ErrorState error={create.error}/>}</form></>}
